# Generated by Django 6.0.3 on 2026-04-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('nota', models.CharField(choices=[('1', '⭐ (1) Ruim'), ('2', '⭐⭐ (2) Regular'), ('3', '⭐⭐⭐ (3) Bom'), ('4', '⭐⭐⭐⭐ (4) Muito Bom'), ('5', '⭐⭐⭐⭐⭐ (5) Excelente')], max_length=1)),
                ('comentario', models.TextField()),
                ('nome_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
            ],
        ),
    ]
